### ISSUE TITLE
Set up CI to run tests

### ISSUE THREAD

**Issue by JohannesLorenz** [JohannesLorenz/ringbuffer#4]
Simply call `make` and `make test`, as described in the `INSTALL` file.

**Comment by Harshil-Jani** [comment]
Hey, I ran this. It works well 👍🏻

**Comment by JohannesLorenz** [comment]
Excellent! There is one more step to do, though. Can you provide a Github Action file in your fork, which executes these steps?

**Comment by Harshil-Jani** [comment]
https://github.com/Harshil-Jani/ringbuffer/actions Yo ! Here we go. 
This is the yml file that you might need to look into 
https://github.com/Harshil-Jani/ringbuffer/blob/Harshil-Jani-patch-1/.github/workflows/c-cpp.yml
